---

- name: Add GitLab repository and key
  ansible.builtin.deb822_repository:
    name: gitlab_gitlab-ce
    types: [deb]
    uris: "{{ gitlab_repo_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: [main]
    architectures: ["{{ ansible_architecture }}"]
    signed_by: "{{ gitlab_key_url }}"
    state: present

- name: Install GitLab
  ansible.builtin.apt:
    name: gitlab-ce
    state: present
  environment:
    EXTERNAL_URL: "{{ gitlab_domain }}"

# TODO: Return secret automatically outside of CI/CD and when explicitly requested

- name: Configure GitLab # TODO: Add filesystem permissions
  ansible.builtin.template:
    src: templates/gitlab.rb.j2
    dest: "{{ gitlab_config_file }}"
    owner: root
    group: root
    mode: "0600"
  notify: Reconfigure GitLab
